### ISSUE TITLE
96boards.ai does not have any clear way to report issues

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/ai#21]
There are no buttons to make it possible to report issues against the 96boards.ai site, nor any other clue on each page which git repo is used to drive this website.

This makes it hard to report problems... and very frustrating for reporters when they are asked to refile against a different repo that is tucked away on the 96boards github.

**Comment by kylekirkby** [comment]
The AI builds are broken currently due to the changes made to the 96board documentation repo. But once Philip picks up the ticket I have raised these will be updated. I can then add links to the 96boards/ai repo.

**Comment by pcolmer** [comment]
@kylekirkby can I have a ticket reference if it still hasn't been resolved?

**Comment by daniel-thompson** [comment]
Not sure about the process behind things but certainly the issue is not resolved: the .ai site has not got the "REPORT an issue" and "EDIT on github" buttons that we normally put on our jekyll based sites.

**Comment by kylekirkby** [comment]
An update to this issue. This will be resolved once we can merge the develop branch into master with this PR - https://github.com/96boards/ai/pull/45 

We need to review site content with Yang first. Scheduling meeting to talk about staging.96boards.ai and any changes we should make first.

Many thanks,

Kyle
