### ISSUE TITLE
Problem with https://www.96boards.ai/products/hikey970/

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/ai#22]
See https://github.com/96boards/website/issues/508

**Comment by pcolmer** [comment]
This issue is still live.

Who is responsible for maintaining the content of the repo/website?

**Comment by daniel-thompson** [comment]
It's a 96Boards website so I guess @Yang-96Boards or @sdrobertw are the ultimate "owner" for this project (although they may have delegated it's maintenance).

**Comment by pcolmer** [comment]
Interestingly, this issue could potentially be solved by https://github.com/96boards/ai/pull/36 but, as I noted in a comment on there, I'm not entirely sure that it is an appropriate change to make.

We really do need more input/oversight from the project owners ...
