### ISSUE TITLE
Building the site pulls in assets and js?

### ISSUE THREAD

**Issue by pcolmer** [96boards/ai#39]
I'm testing the new containerised build mechanism. I'm cloning a clean AI repo, adding the build script and then running it. Afterwards, git reports that a whole bunch of files have been added in a directory called assets and a directory called js.

It seems to me that either those two directories should be added to the .gitignore file or, possibly more likely, they should be added to the built site and not the repo directory?

**Comment by kylekirkby** [comment]
Thanks Philip I'll take a look at this soon - just working on rebasing the Linaro.org website repo...
